name: Isometric Commit Calendar
on:
  # ğŸŒ Schedule updates (once every 24h)
  schedule: [{cron: "0 0 * * *"}]
  # ğŸ–±ï¸ Run manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your Personal Token (Crucial!)
          token: ${{ secrets.TOKEN }}
          
          # ğŸ–¼ï¸ Output File Name
          filename: metrics.plugin.isocalendar.svg
          
          # ğŸš« Disable basic stats (we have them elsewhere)
          base: ""
          
          # ğŸ§© Plugin: Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
